import { c as create_ssr_component, e as escape } from "../../../chunks/ssr.js";
const css = {
  code: ".Login.svelte-vwwwl.svelte-vwwwl{width:400px;margin:100px auto;background:rgb(189,59,11)}.Login.svelte-vwwwl .title.svelte-vwwwl{text-align:center;font:18px/1.5 Koulen, Oswald;padding:5px;border-bottom:1px solid white;color:white}.Login.svelte-vwwwl form.svelte-vwwwl{padding:20px 20px;display:grid;grid-template-columns:20% auto;grid-gap:5px;align-items:center}.Login.svelte-vwwwl form span.svelte-vwwwl{text-align:right;color:white}.Login.svelte-vwwwl form input.svelte-vwwwl{padding:0 5px;font:var(--body-font)}.Login.svelte-vwwwl .info.svelte-vwwwl{text-align:center;color:white}.Login.svelte-vwwwl form input[type=submit].svelte-vwwwl{font:var(--body-font);padding-top:0}@media only screen and (max-width: 600px){.Login.svelte-vwwwl form.svelte-vwwwl{grid-template-columns:100%}.Login.svelte-vwwwl form span.svelte-vwwwl{text-align:left}}",
  map: `{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\r\\nexport let data = {}\\r\\n<\/script>\\r\\n\\r\\n<section class='Login'>\\r\\n    <div class='title'>ចុះ​ឈ្មោះ​ចូល​ផ្នែក​​គ្រប់គ្រង</div>\\r\\n \\r\\n    <form method='post' >\\r\\n        <span>Email:</span><input type='email' name='email' required />\\r\\n        <span>ពាក្យ​សំងាត់ៈ</span><input type='password' name='password' required />\\r\\n        <apan></apan><input type='submit' value='បញ្ជូន' />\\r\\n        <span></span><div class='info'>{data.message || ''}</div>\\r\\n    </form>\\r\\n</section>\\r\\n\\r\\n<style>\\r\\n.Login{\\r\\n    width: 400px;\\r\\n    margin: 100px auto;\\r\\n    background: rgb(189,59,11);\\r\\n} \\r\\n \\r\\n.Login .title{\\r\\n    text-align: center;\\r\\n    font: 18px/1.5 Koulen, Oswald;\\r\\n    padding: 5px;\\r\\n    border-bottom: 1px solid white;\\r\\n    color: white;\\r\\n}\\r\\n \\r\\n.Login form{\\r\\n    padding: 20px 20px;\\r\\n    display: grid;\\r\\n    grid-template-columns: 20% auto; \\r\\n    grid-gap: 5px;\\r\\n    align-items: center;\\r\\n}\\r\\n \\r\\n.Login form span{\\r\\n    text-align: right;\\r\\n    color: white;\\r\\n}\\r\\n \\r\\n.Login form input{\\r\\n    padding: 0 5px;\\r\\n    font: var(--body-font);\\r\\n}\\r\\n \\r\\n.Login .info{\\r\\n    text-align: center;\\r\\n    color: white;\\r\\n}\\r\\n \\r\\n.Login form input[type=submit]{\\r\\n    font: var(--body-font);\\r\\n    padding-top: 0;\\r\\n}\\r\\n \\r\\n@media only screen and (max-width: 600px){\\r\\n    .Login form{\\r\\n        grid-template-columns: 100%; \\r\\n    }\\r\\n \\r\\n    .Login form span{\\r\\n        text-align: left;\\r\\n    }\\r\\n}\\r\\n</style>"],"names":[],"mappings":"AAgBA,gCAAM,CACF,KAAK,CAAE,KAAK,CACZ,MAAM,CAAE,KAAK,CAAC,IAAI,CAClB,UAAU,CAAE,IAAI,GAAG,CAAC,EAAE,CAAC,EAAE,CAC7B,CAEA,mBAAM,CAAC,mBAAM,CACT,UAAU,CAAE,MAAM,CAClB,IAAI,CAAE,IAAI,CAAC,GAAG,CAAC,MAAM,CAAC,CAAC,MAAM,CAC7B,OAAO,CAAE,GAAG,CACZ,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,KAAK,CAC9B,KAAK,CAAE,KACX,CAEA,mBAAM,CAAC,iBAAI,CACP,OAAO,CAAE,IAAI,CAAC,IAAI,CAClB,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,GAAG,CAAC,IAAI,CAC/B,QAAQ,CAAE,GAAG,CACb,WAAW,CAAE,MACjB,CAEA,mBAAM,CAAC,IAAI,CAAC,iBAAI,CACZ,UAAU,CAAE,KAAK,CACjB,KAAK,CAAE,KACX,CAEA,mBAAM,CAAC,IAAI,CAAC,kBAAK,CACb,OAAO,CAAE,CAAC,CAAC,GAAG,CACd,IAAI,CAAE,IAAI,WAAW,CACzB,CAEA,mBAAM,CAAC,kBAAK,CACR,UAAU,CAAE,MAAM,CAClB,KAAK,CAAE,KACX,CAEA,mBAAM,CAAC,IAAI,CAAC,KAAK,CAAC,IAAI,CAAC,MAAM,cAAC,CAC1B,IAAI,CAAE,IAAI,WAAW,CAAC,CACtB,WAAW,CAAE,CACjB,CAEA,OAAO,IAAI,CAAC,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAC,CACrC,mBAAM,CAAC,iBAAI,CACP,qBAAqB,CAAE,IAC3B,CAEA,mBAAM,CAAC,IAAI,CAAC,iBAAI,CACZ,UAAU,CAAE,IAChB,CACJ"}`
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data = {} } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
  $$result.css.add(css);
  return `<section class="Login svelte-vwwwl"><div class="title svelte-vwwwl" data-svelte-h="svelte-1tyb8yb">ចុះ​ឈ្មោះ​ចូល​ផ្នែក​​គ្រប់គ្រង</div> <form method="post" class="svelte-vwwwl"><span class="svelte-vwwwl" data-svelte-h="svelte-1s4kc5o">Email:</span><input type="email" name="email" required class="svelte-vwwwl"> <span class="svelte-vwwwl" data-svelte-h="svelte-1u5gh51">ពាក្យ​សំងាត់ៈ</span><input type="password" name="password" required class="svelte-vwwwl"> <apan></apan><input type="submit" value="បញ្ជូន" class="svelte-vwwwl"> <span class="svelte-vwwwl"></span><div class="info svelte-vwwwl">${escape(data.message || "")}</div></form> </section>`;
});
export {
  Page as default
};
